kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "todo.fullname" . }}-config
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  DB_DIALECT: postgresql
  DB_HOST: {{ .Release.Name }}-postgresql
  DB_NAME: {{ .Values.postgresql.auth.database }}
