apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo.fullname" . }}-secret
  labels:
    {{- include "todo.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.postgresql.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
